/**
 * sdk_block.c -- Block registry and material properties.
 */
#include "sdk_block.h"

#define FACE_COUNT 6
#define ALL_FACES(c) { (c), (c), (c), (c), (c), (c) }

static const SdkBlockDef g_block_defs[BLOCK_COUNT] = {
    {
        BLOCK_AIR, "air", SDK_BLOCK_CLASS_VOID, 0u,
        BLOCK_TOOL_NONE, 0, 0, SDK_COLLAPSE_NONE, 0, 0, 0, 0,
        ITEM_NONE, ALL_FACES(0x00000000u)
    },
    {
        BLOCK_WATER, "water", SDK_BLOCK_CLASS_FLUID,
        SDK_BLOCK_FLAG_FLUID,
        BLOCK_TOOL_NONE, 0, 0, SDK_COLLAPSE_NONE, 255, 0, 0, 0,
        ITEM_BLOCK_WATER, ALL_FACES(0xC0E07028u)
    },
    {
        BLOCK_ICE, "ice", SDK_BLOCK_CLASS_FLUID,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_FULL_CUBE,
        BLOCK_TOOL_PICKAXE, 8, 2, SDK_COLLAPSE_NONE, 16, 20, 20, 10,
        ITEM_BLOCK_SNOW, ALL_FACES(0xE0FFF0D8u)
    },
    {
        BLOCK_SNOW, "snow", SDK_BLOCK_CLASS_SOIL,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_NATURAL,
        BLOCK_TOOL_SHOVEL, 6, 1, SDK_COLLAPSE_LOOSE_SEDIMENT, 80, 70, 5, 0,
        ITEM_BLOCK_SNOW, ALL_FACES(0xFFF4F4F4u)
    },
    {
        BLOCK_BEDROCK, "bedrock", SDK_BLOCK_CLASS_BEDROCK,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_NATURAL,
        BLOCK_TOOL_PICKAXE, 0, 255, SDK_COLLAPSE_COMPETENT_ROCK, 0, 0, 90, 95,
        ITEM_BLOCK_BEDROCK, ALL_FACES(0xFF303030u)
    },
    {
        BLOCK_GRASS, "grass", SDK_BLOCK_CLASS_SOIL,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_NATURAL,
        BLOCK_TOOL_SHOVEL, 18, 8, SDK_COLLAPSE_COMPACT_SEDIMENT, 75, 45, 20, 5,
        ITEM_BLOCK_DIRT, { 0xFF546A44u, 0xFF546A44u, 0xFF68462Bu, 0xFF3EA83Au, 0xFF546A44u, 0xFF546A44u }
    },
    {
        BLOCK_DIRT, "dirt", SDK_BLOCK_CLASS_SOIL,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_NATURAL,
        BLOCK_TOOL_SHOVEL, 16, 8, SDK_COLLAPSE_COMPACT_SEDIMENT, 80, 45, 25, 5,
        ITEM_BLOCK_DIRT, ALL_FACES(0xFF6A4A31u)
    },
    {
        BLOCK_STONE, "stone", SDK_BLOCK_CLASS_ROCK,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_NATURAL,
        BLOCK_TOOL_PICKAXE, 44, 44, SDK_COLLAPSE_COMPETENT_ROCK, 8, 5, 75, 65,
        ITEM_BLOCK_COBBLESTONE, ALL_FACES(0xFF909090u)
    },
    {
        BLOCK_SAND, "sand", SDK_BLOCK_CLASS_SEDIMENT,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_NATURAL,
        BLOCK_TOOL_SHOVEL, 10, 4, SDK_COLLAPSE_LOOSE_SEDIMENT, 190, 65, 10, 0,
        ITEM_BLOCK_SAND, ALL_FACES(0xFFD8CF7Au)
    },
    {
        BLOCK_GRAVEL, "gravel", SDK_BLOCK_CLASS_SEDIMENT,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_NATURAL,
        BLOCK_TOOL_SHOVEL, 18, 12, SDK_COLLAPSE_LOOSE_SEDIMENT, 160, 45, 45, 15,
        ITEM_BLOCK_GRAVEL, ALL_FACES(0xFF808080u)
    },
    {
        BLOCK_LOG, "log", SDK_BLOCK_CLASS_ORGANIC,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_NATURAL | SDK_BLOCK_FLAG_PLACEABLE,
        BLOCK_TOOL_AXE, 28, 6, SDK_COLLAPSE_NONE, 20, 20, 20, 8,
        ITEM_BLOCK_LOG, ALL_FACES(0xFF6A4A2Fu)
    },
    {
        BLOCK_LEAVES, "leaves", SDK_BLOCK_CLASS_ORGANIC,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_NATURAL | SDK_BLOCK_FLAG_PLACEABLE,
        BLOCK_TOOL_AXE, 5, 1, SDK_COLLAPSE_NONE, 200, 60, 0, 0,
        ITEM_BLOCK_LEAVES, ALL_FACES(0xFF3A8840u)
    },
    {
        BLOCK_PLANKS, "planks", SDK_BLOCK_CLASS_CONSTRUCTION,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_PLACEABLE,
        BLOCK_TOOL_AXE, 20, 6, SDK_COLLAPSE_NONE, 15, 10, 45, 20,
        ITEM_BLOCK_PLANKS, ALL_FACES(0xFF9E7A4Eu)
    },
    {
        BLOCK_COBBLESTONE, "cobblestone", SDK_BLOCK_CLASS_CONSTRUCTION,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_PLACEABLE,
        BLOCK_TOOL_PICKAXE, 52, 40, SDK_COLLAPSE_COMPETENT_ROCK, 10, 5, 78, 72,
        ITEM_BLOCK_COBBLESTONE, ALL_FACES(0xFF7C7C7Cu)
    },
    {
        BLOCK_CRAFTING_TABLE, "crafting_table", SDK_BLOCK_CLASS_CONSTRUCTION,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_PLACEABLE,
        BLOCK_TOOL_AXE, 18, 6, SDK_COLLAPSE_NONE, 12, 10, 35, 15,
        ITEM_BLOCK_CRAFTING_TABLE, { 0xFF9E7A4Eu, 0xFF9E7A4Eu, 0xFF805A38u, 0xFFBC9860u, 0xFF9E7A4Eu, 0xFF9E7A4Eu }
    },
    {
        BLOCK_FURNACE, "furnace", SDK_BLOCK_CLASS_CONSTRUCTION,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_PLACEABLE,
        BLOCK_TOOL_PICKAXE, 54, 38, SDK_COLLAPSE_COMPETENT_ROCK, 8, 5, 74, 68,
        ITEM_BLOCK_FURNACE, { 0xFF8E8E8Eu, 0xFF8E8E8Eu, 0xFF6E6E6Eu, 0xFF555555u, 0xFF8E8E8Eu, 0xFF8E8E8Eu }
    },
    {
        BLOCK_CAMPFIRE, "campfire", SDK_BLOCK_CLASS_CONSTRUCTION,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_PLACEABLE,
        BLOCK_TOOL_AXE, 14, 4, SDK_COLLAPSE_NONE, 24, 18, 20, 8,
        ITEM_BLOCK_CAMPFIRE, { 0xFF7A5634u, 0xFF7A5634u, 0xFF4E3626u, 0xFFCC7E34u, 0xFF7A5634u, 0xFF7A5634u }
    },
    {
        BLOCK_ANVIL, "anvil", SDK_BLOCK_CLASS_CONSTRUCTION,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_PLACEABLE,
        BLOCK_TOOL_PICKAXE, 70, 54, SDK_COLLAPSE_COMPETENT_ROCK, 4, 2, 88, 78,
        ITEM_BLOCK_ANVIL, { 0xFF60656Cu, 0xFF60656Cu, 0xFF3F454Cu, 0xFF777E86u, 0xFF60656Cu, 0xFF60656Cu }
    },
    {
        BLOCK_BLACKSMITHING_TABLE, "blacksmithing_table", SDK_BLOCK_CLASS_CONSTRUCTION,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_PLACEABLE,
        BLOCK_TOOL_AXE, 22, 8, SDK_COLLAPSE_NONE, 12, 10, 40, 18,
        ITEM_BLOCK_BLACKSMITHING_TABLE, { 0xFFC0C4CAu, 0xFFC0C4CAu, 0xFF7C5C3Au, 0xFF8E949Cu, 0xFFC0C4CAu, 0xFFC0C4CAu }
    },
    {
        BLOCK_LEATHERWORKING_TABLE, "leatherworking_table", SDK_BLOCK_CLASS_CONSTRUCTION,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_PLACEABLE,
        BLOCK_TOOL_AXE, 20, 7, SDK_COLLAPSE_NONE, 12, 10, 36, 16,
        ITEM_BLOCK_LEATHERWORKING_TABLE, { 0xFF8C6844u, 0xFF8C6844u, 0xFF6E4C34u, 0xFFB28A5Eu, 0xFF8C6844u, 0xFF8C6844u }
    },
    {
        BLOCK_BERRY_BUSH, "berry_bush", SDK_BLOCK_CLASS_ORGANIC,
        SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_NATURAL | SDK_BLOCK_FLAG_PLACEABLE,
        BLOCK_TOOL_AXE, 4, 1, SDK_COLLAPSE_NONE, 180, 40, 0, 0,
        ITEM_BERRIES, ALL_FACES(0xFF4C7C38u)
    },
    {
        BLOCK_REEDS, "reeds", SDK_BLOCK_CLASS_ORGANIC,
        SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_NATURAL | SDK_BLOCK_FLAG_PLACEABLE,
        BLOCK_TOOL_AXE, 3, 1, SDK_COLLAPSE_NONE, 200, 30, 0, 0,
        ITEM_BLOCK_REEDS, ALL_FACES(0xFF7EA64Au)
    },
    {
        BLOCK_COAL_ORE, "coal_ore", SDK_BLOCK_CLASS_RESOURCE,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_RESOURCE | SDK_BLOCK_FLAG_NATURAL,
        BLOCK_TOOL_PICKAXE, 48, 42, SDK_COLLAPSE_COMPETENT_ROCK, 8, 5, 70, 60,
        ITEM_COAL, ALL_FACES(0xFF505050u)
    },
    {
        BLOCK_IRON_ORE, "iron_ore", SDK_BLOCK_CLASS_RESOURCE,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_RESOURCE | SDK_BLOCK_FLAG_NATURAL,
        BLOCK_TOOL_PICKAXE, 54, 46, SDK_COLLAPSE_COMPETENT_ROCK, 8, 5, 72, 62,
        ITEM_BLOCK_IRON_ORE, ALL_FACES(0xFF9C8C78u)
    },
    {
        BLOCK_GRANITE, "granite", SDK_BLOCK_CLASS_ROCK,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_NATURAL,
        BLOCK_TOOL_PICKAXE, 58, 52, SDK_COLLAPSE_COMPETENT_ROCK, 6, 4, 82, 76,
        ITEM_BLOCK_COBBLESTONE, ALL_FACES(0xFF7C8196u)
    },
    {
        BLOCK_GNEISS, "gneiss", SDK_BLOCK_CLASS_ROCK,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_NATURAL,
        BLOCK_TOOL_PICKAXE, 60, 54, SDK_COLLAPSE_COMPETENT_ROCK, 6, 4, 84, 78,
        ITEM_BLOCK_COBBLESTONE, ALL_FACES(0xFF766F73u)
    },
    {
        BLOCK_SCHIST, "schist", SDK_BLOCK_CLASS_ROCK,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_NATURAL,
        BLOCK_TOOL_PICKAXE, 50, 48, SDK_COLLAPSE_FRACTURED_ROCK, 12, 10, 72, 64,
        ITEM_BLOCK_COBBLESTONE, ALL_FACES(0xFF6E646Eu)
    },
    {
        BLOCK_BASALT, "basalt", SDK_BLOCK_CLASS_ROCK,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_NATURAL,
        BLOCK_TOOL_PICKAXE, 56, 50, SDK_COLLAPSE_COMPETENT_ROCK, 5, 4, 88, 70,
        ITEM_BLOCK_COBBLESTONE, ALL_FACES(0xFF4C4A4Au)
    },
    {
        BLOCK_VOLCANIC_ROCK, "volcanic_rock", SDK_BLOCK_CLASS_ROCK,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_NATURAL,
        BLOCK_TOOL_PICKAXE, 52, 48, SDK_COLLAPSE_FRACTURED_ROCK, 16, 8, 70, 55,
        ITEM_BLOCK_COBBLESTONE, ALL_FACES(0xFF5C5554u)
    },
    {
        BLOCK_SANDSTONE, "sandstone", SDK_BLOCK_CLASS_ROCK,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_NATURAL,
        BLOCK_TOOL_PICKAXE, 40, 34, SDK_COLLAPSE_COMPACT_SEDIMENT, 24, 16, 58, 46,
        ITEM_BLOCK_COBBLESTONE, ALL_FACES(0xFFB8AA84u)
    },
    {
        BLOCK_SHALE, "shale", SDK_BLOCK_CLASS_ROCK,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_NATURAL,
        BLOCK_TOOL_PICKAXE, 34, 26, SDK_COLLAPSE_FRACTURED_ROCK, 26, 22, 44, 35,
        ITEM_BLOCK_COBBLESTONE, ALL_FACES(0xFF5E5A64u)
    },
    {
        BLOCK_LIMESTONE, "limestone", SDK_BLOCK_CLASS_ROCK,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_NATURAL,
        BLOCK_TOOL_PICKAXE, 38, 30, SDK_COLLAPSE_COMPACT_SEDIMENT, 20, 18, 62, 48,
        ITEM_LIMESTONE, ALL_FACES(0xFFD4D0BEu)
    },
    {
        BLOCK_DOLOSTONE, "dolostone", SDK_BLOCK_CLASS_ROCK,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_NATURAL,
        BLOCK_TOOL_PICKAXE, 42, 34, SDK_COLLAPSE_COMPACT_SEDIMENT, 18, 16, 66, 52,
        ITEM_LIMESTONE, ALL_FACES(0xFFC4C0B0u)
    },
    {
        BLOCK_MUDSTONE, "mudstone", SDK_BLOCK_CLASS_ROCK,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_NATURAL,
        BLOCK_TOOL_PICKAXE, 28, 20, SDK_COLLAPSE_COMPACT_SEDIMENT, 34, 26, 34, 24,
        ITEM_CLAY, ALL_FACES(0xFF6A5E5Eu)
    },
    {
        BLOCK_SILTSTONE, "siltstone", SDK_BLOCK_CLASS_ROCK,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_NATURAL,
        BLOCK_TOOL_PICKAXE, 32, 24, SDK_COLLAPSE_COMPACT_SEDIMENT, 28, 20, 40, 28,
        ITEM_AGGREGATE, ALL_FACES(0xFF8C7B70u)
    },
    {
        BLOCK_CONGLOMERATE, "conglomerate", SDK_BLOCK_CLASS_ROCK,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_NATURAL,
        BLOCK_TOOL_PICKAXE, 46, 36, SDK_COLLAPSE_COMPACT_SEDIMENT, 18, 12, 64, 42,
        ITEM_AGGREGATE, ALL_FACES(0xFF8A8078u)
    },
    {
        BLOCK_MARL, "marl", SDK_BLOCK_CLASS_ROCK,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_NATURAL,
        BLOCK_TOOL_PICKAXE, 26, 18, SDK_COLLAPSE_COMPACT_SEDIMENT, 24, 28, 32, 22,
        ITEM_LIMESTONE, ALL_FACES(0xFFB9B29Eu)
    },
    {
        BLOCK_CHALK, "chalk", SDK_BLOCK_CLASS_ROCK,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_NATURAL,
        BLOCK_TOOL_PICKAXE, 18, 10, SDK_COLLAPSE_COMPACT_SEDIMENT, 30, 34, 24, 16,
        ITEM_LIMESTONE, ALL_FACES(0xFFE6E2D4u)
    },
    {
        BLOCK_ANDESITE, "andesite", SDK_BLOCK_CLASS_ROCK,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_NATURAL,
        BLOCK_TOOL_PICKAXE, 54, 44, SDK_COLLAPSE_COMPETENT_ROCK, 8, 6, 80, 62,
        ITEM_AGGREGATE, ALL_FACES(0xFF666668u)
    },
    {
        BLOCK_TUFF, "tuff", SDK_BLOCK_CLASS_ROCK,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_NATURAL,
        BLOCK_TOOL_PICKAXE, 24, 14, SDK_COLLAPSE_FRACTURED_ROCK, 48, 26, 30, 18,
        ITEM_AGGREGATE, ALL_FACES(0xFFB7A896u)
    },
    {
        BLOCK_SCORIA, "scoria", SDK_BLOCK_CLASS_ROCK,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_NATURAL,
        BLOCK_TOOL_PICKAXE, 20, 12, SDK_COLLAPSE_FRACTURED_ROCK, 72, 24, 22, 10,
        ITEM_AGGREGATE, ALL_FACES(0xFF4F4442u)
    },
    {
        BLOCK_TOPSOIL, "topsoil", SDK_BLOCK_CLASS_SOIL,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_NATURAL,
        BLOCK_TOOL_SHOVEL, 15, 6, SDK_COLLAPSE_COMPACT_SEDIMENT, 90, 50, 22, 4,
        ITEM_BLOCK_DIRT, ALL_FACES(0xFF704E34u)
    },
    {
        BLOCK_SUBSOIL, "subsoil", SDK_BLOCK_CLASS_SOIL,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_NATURAL,
        BLOCK_TOOL_SHOVEL, 18, 10, SDK_COLLAPSE_COMPACT_SEDIMENT, 85, 45, 28, 5,
        ITEM_BLOCK_DIRT, ALL_FACES(0xFF7A5A3Cu)
    },
    {
        BLOCK_SILT, "silt", SDK_BLOCK_CLASS_SEDIMENT,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_NATURAL,
        BLOCK_TOOL_SHOVEL, 12, 5, SDK_COLLAPSE_LOOSE_SEDIMENT, 100, 55, 14, 2,
        ITEM_CLAY, ALL_FACES(0xFF9A8A72u)
    },
    {
        BLOCK_CLAY, "clay", SDK_BLOCK_CLASS_SEDIMENT,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_NATURAL,
        BLOCK_TOOL_SHOVEL, 16, 8, SDK_COLLAPSE_COMPACT_SEDIMENT, 32, 70, 30, 8,
        ITEM_CLAY, ALL_FACES(0xFF89746Au)
    },
    {
        BLOCK_COARSE_ALLUVIUM, "coarse_alluvium", SDK_BLOCK_CLASS_SEDIMENT,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_NATURAL,
        BLOCK_TOOL_SHOVEL, 20, 12, SDK_COLLAPSE_LOOSE_SEDIMENT, 150, 40, 48, 14,
        ITEM_BLOCK_GRAVEL, ALL_FACES(0xFF8A8478u)
    },
    {
        BLOCK_FINE_ALLUVIUM, "fine_alluvium", SDK_BLOCK_CLASS_SEDIMENT,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_NATURAL,
        BLOCK_TOOL_SHOVEL, 14, 6, SDK_COLLAPSE_COMPACT_SEDIMENT, 96, 54, 22, 5,
        ITEM_CLAY, ALL_FACES(0xFF8A7864u)
    },
    {
        BLOCK_COLLUVIUM, "colluvium", SDK_BLOCK_CLASS_SEDIMENT,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_NATURAL,
        BLOCK_TOOL_SHOVEL, 18, 10, SDK_COLLAPSE_LOOSE_SEDIMENT, 120, 44, 34, 10,
        ITEM_BLOCK_GRAVEL, ALL_FACES(0xFF85786Eu)
    },
    {
        BLOCK_TALUS, "talus", SDK_BLOCK_CLASS_SEDIMENT,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_NATURAL,
        BLOCK_TOOL_SHOVEL, 22, 16, SDK_COLLAPSE_LOOSE_SEDIMENT, 140, 34, 52, 16,
        ITEM_BLOCK_GRAVEL, ALL_FACES(0xFF6E6E74u)
    },
    {
        BLOCK_PEAT, "peat", SDK_BLOCK_CLASS_ORGANIC,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_NATURAL,
        BLOCK_TOOL_SHOVEL, 10, 3, SDK_COLLAPSE_ORGANIC_SOFT, 150, 80, 4, 0,
        ITEM_BLOCK_DIRT, ALL_FACES(0xFF3A2C20u)
    },
    {
        BLOCK_TURF, "turf", SDK_BLOCK_CLASS_ORGANIC,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_NATURAL,
        BLOCK_TOOL_SHOVEL, 14, 5, SDK_COLLAPSE_COMPACT_SEDIMENT, 85, 50, 18, 4,
        ITEM_BLOCK_DIRT, { 0xFF4E603Eu, 0xFF4E603Eu, 0xFF60442Au, 0xFF4C8A36u, 0xFF4E603Eu, 0xFF4E603Eu }
    },
    {
        BLOCK_WETLAND_SOD, "wetland_sod", SDK_BLOCK_CLASS_ORGANIC,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_NATURAL,
        BLOCK_TOOL_SHOVEL, 12, 4, SDK_COLLAPSE_ORGANIC_SOFT, 120, 70, 10, 1,
        ITEM_BLOCK_DIRT, { 0xFF4A5632u, 0xFF4A5632u, 0xFF463126u, 0xFF536E2Cu, 0xFF4A5632u, 0xFF4A5632u }
    },
    {
        BLOCK_MARINE_SAND, "marine_sand", SDK_BLOCK_CLASS_SEDIMENT,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_NATURAL,
        BLOCK_TOOL_SHOVEL, 10, 4, SDK_COLLAPSE_LOOSE_SEDIMENT, 210, 62, 8, 0,
        ITEM_AGGREGATE, ALL_FACES(0xFFD3CC8Au)
    },
    {
        BLOCK_MARINE_MUD, "marine_mud", SDK_BLOCK_CLASS_SEDIMENT,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_NATURAL,
        BLOCK_TOOL_SHOVEL, 12, 4, SDK_COLLAPSE_COMPACT_SEDIMENT, 56, 78, 14, 2,
        ITEM_CLAY, ALL_FACES(0xFF6D655Eu)
    },
    {
        BLOCK_BEACH_GRAVEL, "beach_gravel", SDK_BLOCK_CLASS_SEDIMENT,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_NATURAL,
        BLOCK_TOOL_SHOVEL, 18, 12, SDK_COLLAPSE_LOOSE_SEDIMENT, 175, 42, 50, 14,
        ITEM_AGGREGATE, ALL_FACES(0xFF8D8578u)
    },
    {
        BLOCK_TIDAL_SILT, "tidal_silt", SDK_BLOCK_CLASS_SEDIMENT,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_NATURAL,
        BLOCK_TOOL_SHOVEL, 12, 5, SDK_COLLAPSE_COMPACT_SEDIMENT, 88, 64, 18, 3,
        ITEM_CLAY, ALL_FACES(0xFF7F7768u)
    },
    {
        BLOCK_LOESS, "loess", SDK_BLOCK_CLASS_SOIL,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_NATURAL,
        BLOCK_TOOL_SHOVEL, 12, 5, SDK_COLLAPSE_LOOSE_SEDIMENT, 110, 52, 18, 3,
        ITEM_BLOCK_DIRT, ALL_FACES(0xFFC2B28Eu)
    },
    {
        BLOCK_CALCAREOUS_SOIL, "calcareous_soil", SDK_BLOCK_CLASS_SOIL,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_NATURAL,
        BLOCK_TOOL_SHOVEL, 16, 7, SDK_COLLAPSE_COMPACT_SEDIMENT, 82, 46, 26, 5,
        ITEM_BLOCK_DIRT, ALL_FACES(0xFF9D8A66u)
    },
    {
        BLOCK_SEA_ICE, "sea_ice", SDK_BLOCK_CLASS_FLUID,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_NATURAL,
        BLOCK_TOOL_PICKAXE, 8, 2, SDK_COLLAPSE_NONE, 24, 24, 14, 6,
        ITEM_BLOCK_SNOW, ALL_FACES(0xE8EDF6F4u)
    },
    {
        BLOCK_COAL_SEAM, "coal_seam", SDK_BLOCK_CLASS_RESOURCE,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_RESOURCE | SDK_BLOCK_FLAG_NATURAL,
        BLOCK_TOOL_PICKAXE, 42, 30, SDK_COLLAPSE_FRACTURED_ROCK, 18, 8, 46, 32,
        ITEM_COAL, ALL_FACES(0xFF262626u)
    },
    {
        BLOCK_IRONSTONE, "ironstone", SDK_BLOCK_CLASS_RESOURCE,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_RESOURCE | SDK_BLOCK_FLAG_NATURAL,
        BLOCK_TOOL_PICKAXE, 46, 34, SDK_COLLAPSE_COMPACT_SEDIMENT, 16, 10, 54, 38,
        ITEM_IRONSTONE, ALL_FACES(0xFF8C634Eu)
    },
    {
        BLOCK_CLAY_DEPOSIT, "clay_deposit", SDK_BLOCK_CLASS_RESOURCE,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_RESOURCE | SDK_BLOCK_FLAG_NATURAL,
        BLOCK_TOOL_SHOVEL, 18, 8, SDK_COLLAPSE_COMPACT_SEDIMENT, 24, 72, 32, 8,
        ITEM_CLAY, ALL_FACES(0xFF816C66u)
    },
    {
        BLOCK_COPPER_BEARING_ROCK, "copper_bearing_rock", SDK_BLOCK_CLASS_RESOURCE,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_RESOURCE | SDK_BLOCK_FLAG_NATURAL,
        BLOCK_TOOL_PICKAXE, 50, 40, SDK_COLLAPSE_FRACTURED_ROCK, 12, 8, 64, 48,
        ITEM_COPPER_ORE, ALL_FACES(0xFF7C6A74u)
    },
    {
        BLOCK_SULFUR_BEARING_VOLCANIC_ROCK, "sulfur_bearing_volcanic_rock", SDK_BLOCK_CLASS_RESOURCE,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_RESOURCE | SDK_BLOCK_FLAG_NATURAL,
        BLOCK_TOOL_PICKAXE, 24, 16, SDK_COLLAPSE_FRACTURED_ROCK, 56, 22, 26, 14,
        ITEM_SULFUR, ALL_FACES(0xFF4AB4D6u)
    },
    {
        BLOCK_TUNGSTEN_SKARN, "tungsten_skarn", SDK_BLOCK_CLASS_RESOURCE,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_RESOURCE | SDK_BLOCK_FLAG_NATURAL,
        BLOCK_TOOL_PICKAXE, 62, 56, SDK_COLLAPSE_COMPETENT_ROCK, 10, 6, 80, 66,
        ITEM_TUNGSTEN_ORE, ALL_FACES(0xFF5C5650u)
    },
    {
        BLOCK_BAUXITE, "bauxite", SDK_BLOCK_CLASS_RESOURCE,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_RESOURCE | SDK_BLOCK_FLAG_NATURAL,
        BLOCK_TOOL_PICKAXE, 18, 10, SDK_COLLAPSE_COMPACT_SEDIMENT, 36, 34, 30, 16,
        ITEM_BAUXITE, ALL_FACES(0xFF6E7EB4u)
    },
    {
        BLOCK_LEAD_ZINC_VEIN_ROCK, "lead_zinc_vein_rock", SDK_BLOCK_CLASS_RESOURCE,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_RESOURCE | SDK_BLOCK_FLAG_NATURAL,
        BLOCK_TOOL_PICKAXE, 56, 46, SDK_COLLAPSE_FRACTURED_ROCK, 12, 8, 68, 54,
        ITEM_LEAD_ZINC_ORE, ALL_FACES(0xFF806A84u)
    },
    {
        BLOCK_SALT_EVAPORITE, "salt_evaporite", SDK_BLOCK_CLASS_RESOURCE,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_RESOURCE | SDK_BLOCK_FLAG_NATURAL,
        BLOCK_TOOL_PICKAXE, 16, 8, SDK_COLLAPSE_COMPACT_SEDIMENT, 40, 42, 20, 10,
        ITEM_SALT, ALL_FACES(0xFFF0F0E6u)
    },
    {
        BLOCK_BRECCIA, "breccia", SDK_BLOCK_CLASS_ROCK,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_NATURAL,
        BLOCK_TOOL_PICKAXE, 34, 26, SDK_COLLAPSE_FRACTURED_ROCK, 28, 18, 42, 28,
        ITEM_AGGREGATE, ALL_FACES(0xFF7A6D66u)
    },
    {
        BLOCK_SAPROLITE, "saprolite", SDK_BLOCK_CLASS_SOIL,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_NATURAL,
        BLOCK_TOOL_SHOVEL, 14, 6, SDK_COLLAPSE_COMPACT_SEDIMENT, 68, 56, 20, 4,
        ITEM_BLOCK_DIRT, ALL_FACES(0xFF8C6E54u)
    },
    {
        BLOCK_VEIN_QUARTZ, "vein_quartz", SDK_BLOCK_CLASS_RESOURCE,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_RESOURCE | SDK_BLOCK_FLAG_NATURAL,
        BLOCK_TOOL_PICKAXE, 30, 22, SDK_COLLAPSE_COMPACT_SEDIMENT, 14, 8, 34, 24,
        ITEM_AGGREGATE, ALL_FACES(0xFFE8E3DCu)
    },
    {
        BLOCK_OIL_SHALE, "oil_shale", SDK_BLOCK_CLASS_RESOURCE,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_RESOURCE | SDK_BLOCK_FLAG_NATURAL,
        BLOCK_TOOL_PICKAXE, 24, 18, SDK_COLLAPSE_FRACTURED_ROCK, 18, 10, 30, 18,
        ITEM_NONE, ALL_FACES(0xFF4C443Eu)
    },
    {
        BLOCK_OIL_SAND, "oil_sand", SDK_BLOCK_CLASS_RESOURCE,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_RESOURCE | SDK_BLOCK_FLAG_NATURAL,
        BLOCK_TOOL_SHOVEL, 14, 8, SDK_COLLAPSE_LOOSE_SEDIMENT, 120, 30, 12, 6,
        ITEM_NONE, ALL_FACES(0xFF6A5842u)
    },
    {
        BLOCK_CRUDE_BEARING_SANDSTONE, "crude_bearing_sandstone", SDK_BLOCK_CLASS_RESOURCE,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_RESOURCE | SDK_BLOCK_FLAG_NATURAL,
        BLOCK_TOOL_PICKAXE, 26, 18, SDK_COLLAPSE_COMPACT_SEDIMENT, 20, 10, 34, 22,
        ITEM_NONE, ALL_FACES(0xFF5C4A3Au)
    },
    {
        BLOCK_GAS_BEARING_SANDSTONE, "gas_bearing_sandstone", SDK_BLOCK_CLASS_RESOURCE,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_RESOURCE | SDK_BLOCK_FLAG_NATURAL,
        BLOCK_TOOL_PICKAXE, 24, 18, SDK_COLLAPSE_COMPACT_SEDIMENT, 18, 8, 30, 20,
        ITEM_NONE, ALL_FACES(0xFF7A7F82u)
    },
    {
        BLOCK_RARE_EARTH_ORE, "rare_earth_ore", SDK_BLOCK_CLASS_RESOURCE,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_RESOURCE | SDK_BLOCK_FLAG_NATURAL,
        BLOCK_TOOL_PICKAXE, 46, 38, SDK_COLLAPSE_COMPACT_SEDIMENT, 12, 8, 62, 44,
        ITEM_NONE, ALL_FACES(0xFF857A6Eu)
    },
    {
        BLOCK_URANIUM_ORE, "uranium_ore", SDK_BLOCK_CLASS_RESOURCE,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_RESOURCE | SDK_BLOCK_FLAG_NATURAL,
        BLOCK_TOOL_PICKAXE, 52, 44, SDK_COLLAPSE_COMPETENT_ROCK, 10, 8, 66, 52,
        ITEM_NONE, ALL_FACES(0xFF6A7F52u)
    },
    {
        BLOCK_SALTPETER_BEARING_ROCK, "saltpeter_bearing_rock", SDK_BLOCK_CLASS_RESOURCE,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_RESOURCE | SDK_BLOCK_FLAG_NATURAL,
        BLOCK_TOOL_PICKAXE, 28, 20, SDK_COLLAPSE_COMPACT_SEDIMENT, 22, 14, 36, 22,
        ITEM_NONE, ALL_FACES(0xFFB8B2A0u)
    },
    {
        BLOCK_PHOSPHATE_ROCK, "phosphate_rock", SDK_BLOCK_CLASS_RESOURCE,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_RESOURCE | SDK_BLOCK_FLAG_NATURAL,
        BLOCK_TOOL_PICKAXE, 32, 24, SDK_COLLAPSE_COMPACT_SEDIMENT, 20, 12, 40, 26,
        ITEM_NONE, ALL_FACES(0xFF8F8576u)
    },
    {
        BLOCK_CHROMITE, "chromite", SDK_BLOCK_CLASS_RESOURCE,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_RESOURCE | SDK_BLOCK_FLAG_NATURAL,
        BLOCK_TOOL_PICKAXE, 58, 50, SDK_COLLAPSE_COMPETENT_ROCK, 8, 6, 78, 64,
        ITEM_NONE, ALL_FACES(0xFF5E6268u)
    },
    {
        BLOCK_ALUMINUM_ORE, "aluminum_ore", SDK_BLOCK_CLASS_RESOURCE,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_RESOURCE | SDK_BLOCK_FLAG_NATURAL,
        BLOCK_TOOL_PICKAXE, 42, 34, SDK_COLLAPSE_COMPACT_SEDIMENT, 14, 10, 54, 38,
        ITEM_NONE, ALL_FACES(0xFF7B8596u)
    },
    {
        BLOCK_CRUSHED_STONE, "crushed_stone", SDK_BLOCK_CLASS_CONSTRUCTION,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_PLACEABLE,
        BLOCK_TOOL_SHOVEL, 20, 18, SDK_COLLAPSE_LOOSE_SEDIMENT, 130, 30, 72, 24,
        ITEM_BLOCK_CRUSHED_STONE, ALL_FACES(0xFF8E8E8Eu)
    },
    {
        BLOCK_COMPACTED_FILL, "compacted_fill", SDK_BLOCK_CLASS_CONSTRUCTION,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_PLACEABLE,
        BLOCK_TOOL_SHOVEL, 24, 16, SDK_COLLAPSE_COMPACT_SEDIMENT, 70, 34, 62, 18,
        ITEM_BLOCK_COMPACTED_FILL, ALL_FACES(0xFF8A6C4Eu)
    },
    {
        BLOCK_SANDBAGS, "sandbags", SDK_BLOCK_CLASS_CONSTRUCTION,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_PLACEABLE,
        BLOCK_TOOL_SHOVEL, 18, 6, SDK_COLLAPSE_COMPACT_SEDIMENT, 50, 20, 58, 42,
        ITEM_BLOCK_SANDBAGS, ALL_FACES(0xFFC8B996u)
    },
    {
        BLOCK_BRICK, "brick", SDK_BLOCK_CLASS_CONSTRUCTION,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_PLACEABLE,
        BLOCK_TOOL_PICKAXE, 38, 28, SDK_COLLAPSE_COMPACT_SEDIMENT, 10, 8, 68, 48,
        ITEM_BLOCK_BRICK, ALL_FACES(0xFF944A36u)
    },
    {
        BLOCK_STONE_BRICKS, "stone_bricks", SDK_BLOCK_CLASS_CONSTRUCTION,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_PLACEABLE,
        BLOCK_TOOL_PICKAXE, 58, 42, SDK_COLLAPSE_COMPETENT_ROCK, 8, 5, 86, 74,
        ITEM_BLOCK_STONE_BRICKS, ALL_FACES(0xFF9E9B96u)
    },
    {
        BLOCK_CONCRETE, "concrete", SDK_BLOCK_CLASS_CONSTRUCTION,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_PLACEABLE,
        BLOCK_TOOL_PICKAXE, 62, 50, SDK_COLLAPSE_COMPETENT_ROCK, 6, 4, 88, 82,
        ITEM_BLOCK_CONCRETE, ALL_FACES(0xFFB0B0B0u)
    },
    {
        BLOCK_REINFORCED_CONCRETE, "reinforced_concrete", SDK_BLOCK_CLASS_CONSTRUCTION,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_PLACEABLE,
        BLOCK_TOOL_PICKAXE, 75, 62, SDK_COLLAPSE_COMPETENT_ROCK, 4, 2, 95, 94,
        ITEM_BLOCK_REINFORCED_CONCRETE, ALL_FACES(0xFF8E949Cu)
    },
    {
        BLOCK_LAVA, "lava", SDK_BLOCK_CLASS_FLUID,
        SDK_BLOCK_FLAG_FLUID | SDK_BLOCK_FLAG_NATURAL,
        BLOCK_TOOL_NONE, 0, 0, SDK_COLLAPSE_NONE, 255, 0, 0, 0,
        ITEM_NONE, ALL_FACES(0xFFE05A18u)
    },
    {
        BLOCK_TALL_GRASS, "tall_grass", SDK_BLOCK_CLASS_ORGANIC,
        SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_NATURAL | SDK_BLOCK_FLAG_PLACEABLE,
        BLOCK_TOOL_AXE, 2, 1, SDK_COLLAPSE_NONE, 210, 35, 0, 0,
        ITEM_NONE, ALL_FACES(0xFF5E9B42u)
    },
    {
        BLOCK_DRY_GRASS, "dry_grass", SDK_BLOCK_CLASS_ORGANIC,
        SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_NATURAL | SDK_BLOCK_FLAG_PLACEABLE,
        BLOCK_TOOL_AXE, 2, 1, SDK_COLLAPSE_NONE, 210, 25, 0, 0,
        ITEM_NONE, ALL_FACES(0xFFBBA35Au)
    },
    {
        BLOCK_FERN, "fern", SDK_BLOCK_CLASS_ORGANIC,
        SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_NATURAL | SDK_BLOCK_FLAG_PLACEABLE,
        BLOCK_TOOL_AXE, 2, 1, SDK_COLLAPSE_NONE, 215, 40, 0, 0,
        ITEM_NONE, ALL_FACES(0xFF4E8A4Eu)
    },
    {
        BLOCK_SHRUB, "shrub", SDK_BLOCK_CLASS_ORGANIC,
        SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_NATURAL | SDK_BLOCK_FLAG_PLACEABLE,
        BLOCK_TOOL_AXE, 3, 2, SDK_COLLAPSE_NONE, 180, 30, 0, 0,
        ITEM_NONE, ALL_FACES(0xFF7A8C44u)
    },
    {
        BLOCK_HEATHER, "heather", SDK_BLOCK_CLASS_ORGANIC,
        SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_NATURAL | SDK_BLOCK_FLAG_PLACEABLE,
        BLOCK_TOOL_AXE, 2, 1, SDK_COLLAPSE_NONE, 190, 34, 0, 0,
        ITEM_NONE, ALL_FACES(0xFF8A6A8Eu)
    },
    {
        BLOCK_CATTAILS, "cattails", SDK_BLOCK_CLASS_ORGANIC,
        SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_NATURAL | SDK_BLOCK_FLAG_PLACEABLE,
        BLOCK_TOOL_AXE, 2, 1, SDK_COLLAPSE_NONE, 215, 35, 0, 0,
        ITEM_NONE, ALL_FACES(0xFF8D7A36u)
    },
    {
        BLOCK_WILDFLOWERS, "wildflowers", SDK_BLOCK_CLASS_ORGANIC,
        SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_NATURAL | SDK_BLOCK_FLAG_PLACEABLE,
        BLOCK_TOOL_AXE, 2, 1, SDK_COLLAPSE_NONE, 205, 32, 0, 0,
        ITEM_NONE, ALL_FACES(0xFFC76A6Au)
    },
    {
        BLOCK_CACTUS, "cactus", SDK_BLOCK_CLASS_ORGANIC,
        SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_NATURAL | SDK_BLOCK_FLAG_PLACEABLE,
        BLOCK_TOOL_AXE, 6, 4, SDK_COLLAPSE_NONE, 80, 18, 6, 2,
        ITEM_NONE, ALL_FACES(0xFF3F8A46u)
    },
    {
        BLOCK_SUCCULENT, "succulent", SDK_BLOCK_CLASS_ORGANIC,
        SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_NATURAL | SDK_BLOCK_FLAG_PLACEABLE,
        BLOCK_TOOL_AXE, 3, 2, SDK_COLLAPSE_NONE, 175, 20, 0, 0,
        ITEM_NONE, ALL_FACES(0xFF6FA062u)
    },
    {
        BLOCK_MOSS, "moss", SDK_BLOCK_CLASS_ORGANIC,
        SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_NATURAL | SDK_BLOCK_FLAG_PLACEABLE,
        BLOCK_TOOL_AXE, 2, 1, SDK_COLLAPSE_NONE, 165, 42, 0, 0,
        ITEM_NONE, ALL_FACES(0xFF3E7440u)
    },
    {
        BLOCK_TIMBER_LIGHT, "timber_light", SDK_BLOCK_CLASS_CONSTRUCTION,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_PLACEABLE,
        BLOCK_TOOL_AXE, 24, 8, SDK_COLLAPSE_NONE, 12, 10, 42, 20,
        ITEM_BLOCK_TIMBER_LIGHT, ALL_FACES(0xFFC8A070u)
    },
    {
        BLOCK_TIMBER_DARK, "timber_dark", SDK_BLOCK_CLASS_CONSTRUCTION,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_PLACEABLE,
        BLOCK_TOOL_AXE, 26, 8, SDK_COLLAPSE_NONE, 12, 10, 44, 22,
        ITEM_BLOCK_TIMBER_DARK, ALL_FACES(0xFF755338u)
    },
    {
        BLOCK_TIMBER_WEATHERED, "timber_weathered", SDK_BLOCK_CLASS_CONSTRUCTION,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_PLACEABLE,
        BLOCK_TOOL_AXE, 24, 8, SDK_COLLAPSE_NONE, 14, 12, 38, 18,
        ITEM_BLOCK_TIMBER_WEATHERED, ALL_FACES(0xFF8E816Eu)
    },
    {
        BLOCK_THATCH, "thatch", SDK_BLOCK_CLASS_CONSTRUCTION,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_PLACEABLE,
        BLOCK_TOOL_AXE, 10, 2, SDK_COLLAPSE_NONE, 28, 24, 10, 4,
        ITEM_BLOCK_THATCH, ALL_FACES(0xFFD4BC6Au)
    },
    {
        BLOCK_WOOD_SHINGLES, "wood_shingles", SDK_BLOCK_CLASS_CONSTRUCTION,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_PLACEABLE,
        BLOCK_TOOL_AXE, 18, 6, SDK_COLLAPSE_NONE, 14, 10, 34, 16,
        ITEM_BLOCK_WOOD_SHINGLES, ALL_FACES(0xFF8A6548u)
    },
    {
        BLOCK_WATTLE_DAUB, "wattle_daub", SDK_BLOCK_CLASS_CONSTRUCTION,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_PLACEABLE,
        BLOCK_TOOL_SHOVEL, 14, 6, SDK_COLLAPSE_COMPACT_SEDIMENT, 40, 28, 28, 8,
        ITEM_BLOCK_WATTLE_DAUB, ALL_FACES(0xFFC09C70u)
    },
    {
        BLOCK_ADOBE, "adobe", SDK_BLOCK_CLASS_CONSTRUCTION,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_PLACEABLE,
        BLOCK_TOOL_SHOVEL, 18, 10, SDK_COLLAPSE_COMPACT_SEDIMENT, 34, 24, 34, 12,
        ITEM_BLOCK_ADOBE, ALL_FACES(0xFFD0A172u)
    },
    {
        BLOCK_MUDBRICK, "mudbrick", SDK_BLOCK_CLASS_CONSTRUCTION,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_PLACEABLE,
        BLOCK_TOOL_SHOVEL, 20, 12, SDK_COLLAPSE_COMPACT_SEDIMENT, 28, 20, 40, 14,
        ITEM_BLOCK_MUDBRICK, ALL_FACES(0xFF9E6E4Eu)
    },
    {
        BLOCK_PLASTER_WHITE, "plaster_white", SDK_BLOCK_CLASS_CONSTRUCTION,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_PLACEABLE,
        BLOCK_TOOL_SHOVEL, 16, 8, SDK_COLLAPSE_COMPACT_SEDIMENT, 20, 12, 24, 10,
        ITEM_BLOCK_PLASTER_WHITE, ALL_FACES(0xFFF0ECE2u)
    },
    {
        BLOCK_PLASTER_OCHRE, "plaster_ochre", SDK_BLOCK_CLASS_CONSTRUCTION,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_PLACEABLE,
        BLOCK_TOOL_SHOVEL, 16, 8, SDK_COLLAPSE_COMPACT_SEDIMENT, 20, 12, 24, 10,
        ITEM_BLOCK_PLASTER_OCHRE, ALL_FACES(0xFFD6B06Eu)
    },
    {
        BLOCK_CUT_STONE_LIGHT, "cut_stone_light", SDK_BLOCK_CLASS_CONSTRUCTION,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_PLACEABLE,
        BLOCK_TOOL_PICKAXE, 52, 40, SDK_COLLAPSE_COMPETENT_ROCK, 8, 6, 82, 72,
        ITEM_BLOCK_CUT_STONE_LIGHT, ALL_FACES(0xFFD2CABEu)
    },
    {
        BLOCK_CUT_STONE_DARK, "cut_stone_dark", SDK_BLOCK_CLASS_CONSTRUCTION,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_PLACEABLE,
        BLOCK_TOOL_PICKAXE, 56, 44, SDK_COLLAPSE_COMPETENT_ROCK, 8, 6, 84, 74,
        ITEM_BLOCK_CUT_STONE_DARK, ALL_FACES(0xFF686462u)
    },
    {
        BLOCK_RUBBLE_MASONRY, "rubble_masonry", SDK_BLOCK_CLASS_CONSTRUCTION,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_PLACEABLE,
        BLOCK_TOOL_PICKAXE, 48, 36, SDK_COLLAPSE_COMPETENT_ROCK, 10, 6, 74, 62,
        ITEM_BLOCK_RUBBLE_MASONRY, ALL_FACES(0xFF857E78u)
    },
    {
        BLOCK_FLAGSTONE, "flagstone", SDK_BLOCK_CLASS_CONSTRUCTION,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_PLACEABLE,
        BLOCK_TOOL_PICKAXE, 42, 30, SDK_COLLAPSE_COMPETENT_ROCK, 10, 6, 68, 56,
        ITEM_BLOCK_FLAGSTONE, ALL_FACES(0xFFA09A90u)
    },
    {
        BLOCK_CLAY_ROOF_TILE, "clay_roof_tile", SDK_BLOCK_CLASS_CONSTRUCTION,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_PLACEABLE,
        BLOCK_TOOL_PICKAXE, 24, 14, SDK_COLLAPSE_COMPACT_SEDIMENT, 14, 10, 36, 18,
        ITEM_BLOCK_CLAY_ROOF_TILE, ALL_FACES(0xFFB45A3Eu)
    },
    {
        BLOCK_SLATE_ROOF, "slate_roof", SDK_BLOCK_CLASS_CONSTRUCTION,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_PLACEABLE,
        BLOCK_TOOL_PICKAXE, 34, 24, SDK_COLLAPSE_COMPETENT_ROCK, 10, 6, 52, 34,
        ITEM_BLOCK_SLATE_ROOF, ALL_FACES(0xFF50545Eu)
    },
    {
        BLOCK_CORRUGATED_METAL, "corrugated_metal", SDK_BLOCK_CLASS_CONSTRUCTION,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_PLACEABLE,
        BLOCK_TOOL_PICKAXE, 30, 18, SDK_COLLAPSE_NONE, 2, 0, 54, 26,
        ITEM_BLOCK_CORRUGATED_METAL, ALL_FACES(0xFF88939Eu)
    },
    {
        BLOCK_WROUGHT_IRON, "wrought_iron", SDK_BLOCK_CLASS_CONSTRUCTION,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_PLACEABLE,
        BLOCK_TOOL_PICKAXE, 34, 20, SDK_COLLAPSE_NONE, 2, 0, 56, 28,
        ITEM_BLOCK_WROUGHT_IRON, ALL_FACES(0xFF4C545Cu)
    },
    {
        BLOCK_GLASS, "glass", SDK_BLOCK_CLASS_CONSTRUCTION,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_PLACEABLE,
        BLOCK_TOOL_PICKAXE, 10, 4, SDK_COLLAPSE_NONE, 1, 0, 18, 8,
        ITEM_BLOCK_GLASS, ALL_FACES(0x90D8EEF6u)
    },
    {
        BLOCK_ROPE_NETTING, "rope_netting", SDK_BLOCK_CLASS_CONSTRUCTION,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_PLACEABLE,
        BLOCK_TOOL_AXE, 8, 2, SDK_COLLAPSE_NONE, 24, 18, 8, 2,
        ITEM_BLOCK_ROPE_NETTING, ALL_FACES(0x90B89A6Au)
    },
    {
        BLOCK_COLOR_WHITE, "color_white", SDK_BLOCK_CLASS_CONSTRUCTION,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_PLACEABLE,
        BLOCK_TOOL_NONE, 6, 1, SDK_COLLAPSE_NONE, 0, 0, 18, 8,
        ITEM_NONE, ALL_FACES(0xFFF4F4F4u)
    },
    {
        BLOCK_COLOR_BLACK, "color_black", SDK_BLOCK_CLASS_CONSTRUCTION,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_PLACEABLE,
        BLOCK_TOOL_NONE, 6, 1, SDK_COLLAPSE_NONE, 0, 0, 18, 8,
        ITEM_NONE, ALL_FACES(0xFF1A1A1Au)
    },
    {
        BLOCK_COLOR_RED, "color_red", SDK_BLOCK_CLASS_CONSTRUCTION,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_PLACEABLE,
        BLOCK_TOOL_NONE, 6, 1, SDK_COLLAPSE_NONE, 0, 0, 18, 8,
        ITEM_NONE, ALL_FACES(0xFFC84848u)
    },
    {
        BLOCK_COLOR_ORANGE, "color_orange", SDK_BLOCK_CLASS_CONSTRUCTION,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_PLACEABLE,
        BLOCK_TOOL_NONE, 6, 1, SDK_COLLAPSE_NONE, 0, 0, 18, 8,
        ITEM_NONE, ALL_FACES(0xFFD8873Au)
    },
    {
        BLOCK_COLOR_YELLOW, "color_yellow", SDK_BLOCK_CLASS_CONSTRUCTION,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_PLACEABLE,
        BLOCK_TOOL_NONE, 6, 1, SDK_COLLAPSE_NONE, 0, 0, 18, 8,
        ITEM_NONE, ALL_FACES(0xFFE6D85Au)
    },
    {
        BLOCK_COLOR_GREEN, "color_green", SDK_BLOCK_CLASS_CONSTRUCTION,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_PLACEABLE,
        BLOCK_TOOL_NONE, 6, 1, SDK_COLLAPSE_NONE, 0, 0, 18, 8,
        ITEM_NONE, ALL_FACES(0xFF4EAE62u)
    },
    {
        BLOCK_COLOR_CYAN, "color_cyan", SDK_BLOCK_CLASS_CONSTRUCTION,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_PLACEABLE,
        BLOCK_TOOL_NONE, 6, 1, SDK_COLLAPSE_NONE, 0, 0, 18, 8,
        ITEM_NONE, ALL_FACES(0xFF56C8D4u)
    },
    {
        BLOCK_COLOR_BLUE, "color_blue", SDK_BLOCK_CLASS_CONSTRUCTION,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_PLACEABLE,
        BLOCK_TOOL_NONE, 6, 1, SDK_COLLAPSE_NONE, 0, 0, 18, 8,
        ITEM_NONE, ALL_FACES(0xFF4D70D8u)
    },
    {
        BLOCK_COLOR_PURPLE, "color_purple", SDK_BLOCK_CLASS_CONSTRUCTION,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_PLACEABLE,
        BLOCK_TOOL_NONE, 6, 1, SDK_COLLAPSE_NONE, 0, 0, 18, 8,
        ITEM_NONE, ALL_FACES(0xFF9056D4u)
    },
    {
        BLOCK_COLOR_PINK, "color_pink", SDK_BLOCK_CLASS_CONSTRUCTION,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_PLACEABLE,
        BLOCK_TOOL_NONE, 6, 1, SDK_COLLAPSE_NONE, 0, 0, 18, 8,
        ITEM_NONE, ALL_FACES(0xFFD88ABEu)
    },
    {
        BLOCK_COLOR_BROWN, "color_brown", SDK_BLOCK_CLASS_CONSTRUCTION,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_PLACEABLE,
        BLOCK_TOOL_NONE, 6, 1, SDK_COLLAPSE_NONE, 0, 0, 18, 8,
        ITEM_NONE, ALL_FACES(0xFF7E5A42u)
    },
    {
        BLOCK_COLOR_GRAY, "color_gray", SDK_BLOCK_CLASS_CONSTRUCTION,
        SDK_BLOCK_FLAG_SOLID | SDK_BLOCK_FLAG_OPAQUE | SDK_BLOCK_FLAG_FULL_CUBE | SDK_BLOCK_FLAG_PLACEABLE,
        BLOCK_TOOL_NONE, 6, 1, SDK_COLLAPSE_NONE, 0, 0, 18, 8,
        ITEM_NONE, ALL_FACES(0xFF808892u)
    }
};

static const SdkBlockDef* block_def_or_air(BlockType type)
{
    if ((int)type < 0 || type >= BLOCK_COUNT) {
        return &g_block_defs[BLOCK_AIR];
    }
    if (g_block_defs[type].id != type) {
        for (int i = 0; i < BLOCK_COUNT; ++i) {
            if (g_block_defs[i].id == type) {
                return &g_block_defs[i];
            }
        }
        return &g_block_defs[BLOCK_AIR];
    }
    return &g_block_defs[type];
}

const SdkBlockDef* sdk_block_get_def(BlockType type)
{
    return block_def_or_air(type);
}

const char* sdk_block_get_name(BlockType type)
{
    return block_def_or_air(type)->name;
}

const char* sdk_block_get_texture_asset(BlockType type, int face)
{
    if (face < 0 || face >= FACE_COUNT) face = 0;

    switch (type) {
        case BLOCK_GRASS:
            if (face == 3) return "grass_top";
            if (face == 2) return "dirt";
            return "grass_side";
        case BLOCK_TURF:
            if (face == 3) return "turf_top";
            if (face == 2) return "dirt";
            return "turf_side";
        case BLOCK_WETLAND_SOD:
            if (face == 3) return "wetland_sod_top";
            if (face == 2) return "dirt";
            return "wetland_sod_side";
        case BLOCK_LOG:
            if (face == 3 || face == 2) return "log_top";
            return "log_side";
        case BLOCK_CRAFTING_TABLE:
            if (face == 3) return "crafting_table_top";
            if (face == 2) return "planks";
            return "crafting_table_side";
        case BLOCK_FURNACE:
            if (face == 3) return "furnace_top";
            if (face == 2) return "furnace_bottom";
            return "furnace_side";
        case BLOCK_CAMPFIRE:
            if (face == 3) return "campfire_top";
            if (face == 2) return "campfire_bottom";
            return "campfire_side";
        case BLOCK_ANVIL:
            if (face == 3) return "anvil_top";
            if (face == 2) return "anvil_bottom";
            return "anvil_side";
        case BLOCK_BLACKSMITHING_TABLE:
            if (face == 3) return "blacksmithing_table_top";
            if (face == 2) return "blacksmithing_table_bottom";
            return "blacksmithing_table_side";
        case BLOCK_LEATHERWORKING_TABLE:
            if (face == 3) return "leatherworking_table_top";
            if (face == 2) return "leatherworking_table_bottom";
            return "leatherworking_table_side";
        default:
            return block_def_or_air(type)->name;
    }
}

BlockColor sdk_block_get_color(BlockType type)
{
    return block_def_or_air(type)->face_color[0];
}

BlockColor sdk_block_get_face_color(BlockType type, int face)
{
    const SdkBlockDef* def = block_def_or_air(type);
    if (face < 0 || face >= FACE_COUNT) return def->face_color[0];
    return def->face_color[face];
}

int sdk_block_get_hardness(BlockType type)
{
    return (int)block_def_or_air(type)->hardness;
}

int sdk_block_is_solid(BlockType type)
{
    return (block_def_or_air(type)->flags & SDK_BLOCK_FLAG_SOLID) != 0u;
}

int sdk_block_is_full(BlockType type)
{
    return (block_def_or_air(type)->flags & SDK_BLOCK_FLAG_FULL_CUBE) != 0u;
}

int sdk_block_is_opaque(BlockType type)
{
    return (block_def_or_air(type)->flags & SDK_BLOCK_FLAG_OPAQUE) != 0u;
}

BlockToolPref sdk_block_get_tool_pref(BlockType type)
{
    return block_def_or_air(type)->tool_pref;
}

ItemType sdk_block_get_drop_item(BlockType type)
{
    return block_def_or_air(type)->drop_item;
}

int sdk_block_is_color(BlockType type)
{
    return type >= BLOCK_COLOR_WHITE && type <= BLOCK_COLOR_GRAY;
}

SdkRuntimeMaterialClass sdk_block_get_runtime_material(BlockType type)
{
    switch (type) {
        case BLOCK_WATER:
            return SDK_MATERIAL_FLUID_WATER;
        case BLOCK_LAVA:
            return SDK_MATERIAL_FLUID_LAVA;
        case BLOCK_SAND:
        case BLOCK_GRAVEL:
        case BLOCK_COARSE_ALLUVIUM:
        case BLOCK_TALUS:
        case BLOCK_BEACH_GRAVEL:
        case BLOCK_MARINE_SAND:
            return SDK_MATERIAL_GRANULAR_LOOSE;
        case BLOCK_COLLUVIUM:
        case BLOCK_CRUSHED_STONE:
        case BLOCK_SANDBAGS:
            return SDK_MATERIAL_GRANULAR_COMPACTED;
        case BLOCK_TOPSOIL:
        case BLOCK_SUBSOIL:
        case BLOCK_CLAY:
        case BLOCK_FINE_ALLUVIUM:
        case BLOCK_MARINE_MUD:
        case BLOCK_TIDAL_SILT:
        case BLOCK_WETLAND_SOD:
        case BLOCK_PEAT:
        case BLOCK_BERRY_BUSH:
        case BLOCK_REEDS:
        case BLOCK_TALL_GRASS:
        case BLOCK_DRY_GRASS:
        case BLOCK_FERN:
        case BLOCK_SHRUB:
        case BLOCK_HEATHER:
        case BLOCK_CATTAILS:
        case BLOCK_WILDFLOWERS:
        case BLOCK_CACTUS:
        case BLOCK_SUCCULENT:
        case BLOCK_MOSS:
            return SDK_MATERIAL_ORGANIC_SOFT;
        case BLOCK_SHALE:
        case BLOCK_MUDSTONE:
        case BLOCK_SILTSTONE:
        case BLOCK_MARL:
        case BLOCK_CHALK:
        case BLOCK_TUFF:
        case BLOCK_SCORIA:
        case BLOCK_SALT_EVAPORITE:
        case BLOCK_SAPROLITE:
            return SDK_MATERIAL_STATIC_WEAK;
        default:
            return SDK_MATERIAL_STATIC_COMPETENT;
    }
}

uint32_t sdk_block_get_behavior_flags(BlockType type)
{
    switch (sdk_block_get_runtime_material(type)) {
        case SDK_MATERIAL_FLUID_WATER:
        case SDK_MATERIAL_FLUID_LAVA:
            return SDK_BLOCK_BEHAVIOR_FLUID;
        case SDK_MATERIAL_GRANULAR_LOOSE:
            return SDK_BLOCK_BEHAVIOR_GRANULAR | SDK_BLOCK_BEHAVIOR_SUPPORT_SENSITIVE;
        case SDK_MATERIAL_GRANULAR_COMPACTED:
        case SDK_MATERIAL_STATIC_WEAK:
        case SDK_MATERIAL_ORGANIC_SOFT:
            return SDK_BLOCK_BEHAVIOR_SUPPORT_SENSITIVE;
        case SDK_MATERIAL_STATIC_COMPETENT:
        default:
            return 0u;
    }
}

uint8_t sdk_block_get_settling_rate(BlockType type)
{
    switch (sdk_block_get_runtime_material(type)) {
        case SDK_MATERIAL_FLUID_WATER:
            return 255u;
        case SDK_MATERIAL_FLUID_LAVA:
            return 48u;
        case SDK_MATERIAL_GRANULAR_LOOSE:
            return 180u;
        case SDK_MATERIAL_GRANULAR_COMPACTED:
            return 96u;
        default:
            return 0u;
    }
}

uint8_t sdk_block_get_angle_of_repose(BlockType type)
{
    switch (type) {
        case BLOCK_SAND:
        case BLOCK_MARINE_SAND:
            return 34u;
        case BLOCK_GRAVEL:
        case BLOCK_BEACH_GRAVEL:
        case BLOCK_COARSE_ALLUVIUM:
            return 38u;
        case BLOCK_TALUS:
        case BLOCK_CRUSHED_STONE:
            return 41u;
        case BLOCK_COLLUVIUM:
            return 36u;
        default:
            return 32u;
    }
}

uint8_t sdk_block_get_fluid_viscosity(BlockType type)
{
    switch (type) {
        case BLOCK_WATER:
            return 12u;
        case BLOCK_LAVA:
            return 220u;
        default:
            return 0u;
    }
}
