/**
 * sdk_worldgen_types.h -- Public worldgen enums and sampled column profile.
 */
#ifndef NQLSDK_WORLDGEN_TYPES_H
#define NQLSDK_WORLDGEN_TYPES_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
    TERRAIN_PROVINCE_OPEN_OCEAN = 0,
    TERRAIN_PROVINCE_CONTINENTAL_SHELF,
    TERRAIN_PROVINCE_DYNAMIC_COAST,
    TERRAIN_PROVINCE_ESTUARY_DELTA,
    TERRAIN_PROVINCE_FLOODPLAIN_ALLUVIAL_LOWLAND,
    TERRAIN_PROVINCE_PEAT_WETLAND,
    TERRAIN_PROVINCE_SILICICLASTIC_HILLS,
    TERRAIN_PROVINCE_CARBONATE_UPLAND,
    TERRAIN_PROVINCE_HARDROCK_HIGHLAND,
    TERRAIN_PROVINCE_UPLIFTED_PLATEAU,
    TERRAIN_PROVINCE_RIFT_VALLEY,
    TERRAIN_PROVINCE_FOLD_MOUNTAIN_BELT,
    TERRAIN_PROVINCE_VOLCANIC_ARC,
    TERRAIN_PROVINCE_BASALT_PLATEAU,
    TERRAIN_PROVINCE_ARID_FAN_STEPPE,
    TERRAIN_PROVINCE_ALPINE_BELT,
    TERRAIN_PROVINCE_SALT_FLAT_PLAYA,
    TERRAIN_PROVINCE_BADLANDS_DISSECTED
} SdkTerrainProvince;

typedef enum {
    BEDROCK_PROVINCE_OCEANIC_BASALT = 0,
    BEDROCK_PROVINCE_CRATON_GRANITE_GNEISS,
    BEDROCK_PROVINCE_METAMORPHIC_BELT,
    BEDROCK_PROVINCE_GRANITIC_INTRUSIVE,
    BEDROCK_PROVINCE_SILICICLASTIC_BASIN,
    BEDROCK_PROVINCE_CARBONATE_PLATFORM,
    BEDROCK_PROVINCE_RIFT_SEDIMENTARY,
    BEDROCK_PROVINCE_VOLCANIC_ARC,
    BEDROCK_PROVINCE_FLOOD_BASALT
} SdkBedrockProvince;

typedef enum {
    TEMP_POLAR = 0,
    TEMP_SUBPOLAR,
    TEMP_COOL_TEMPERATE,
    TEMP_WARM_TEMPERATE,
    TEMP_SUBTROPICAL,
    TEMP_TROPICAL
} SdkTemperatureBand;

typedef enum {
    MOISTURE_ARID = 0,
    MOISTURE_SEMI_ARID,
    MOISTURE_SUBHUMID,
    MOISTURE_HUMID,
    MOISTURE_PERHUMID,
    MOISTURE_WATERLOGGED
} SdkMoistureBand;

typedef enum {
    SEDIMENT_NONE = 0,
    SEDIMENT_RESIDUAL_SOIL,
    SEDIMENT_COLLUVIUM,
    SEDIMENT_TALUS,
    SEDIMENT_COARSE_ALLUVIUM,
    SEDIMENT_FINE_ALLUVIUM,
    SEDIMENT_DELTAIC_SILT,
    SEDIMENT_LACUSTRINE_CLAY,
    SEDIMENT_BEACH_SAND,
    SEDIMENT_EOILIAN_SAND,
    SEDIMENT_PEAT,
    SEDIMENT_VOLCANIC_ASH,
    SEDIMENT_MARINE_MUD,
    SEDIMENT_MARINE_SAND,
    SEDIMENT_LOESS,
    SEDIMENT_CALCAREOUS_RESIDUAL,
    SEDIMENT_SAPROLITE
} SdkSurfaceSediment;

typedef enum {
    PARENT_MATERIAL_NONE = 0,
    PARENT_MATERIAL_GRANITIC,
    PARENT_MATERIAL_METAMORPHIC,
    PARENT_MATERIAL_MAFIC_VOLCANIC,
    PARENT_MATERIAL_INTERMEDIATE_VOLCANIC,
    PARENT_MATERIAL_SILICICLASTIC,
    PARENT_MATERIAL_CARBONATE,
    PARENT_MATERIAL_ORGANIC,
    PARENT_MATERIAL_ALLUVIAL,
    PARENT_MATERIAL_AEOLIAN,
    PARENT_MATERIAL_EVAPORITIC
} SdkParentMaterialClass;

typedef enum {
    DRAINAGE_EXCESSIVE = 0,
    DRAINAGE_WELL,
    DRAINAGE_MODERATE,
    DRAINAGE_IMPERFECT,
    DRAINAGE_POOR,
    DRAINAGE_WATERLOGGED
} SdkDrainageClass;

typedef enum {
    SOIL_REACTION_STRONGLY_ACID = 0,
    SOIL_REACTION_ACID,
    SOIL_REACTION_SLIGHTLY_ACID,
    SOIL_REACTION_NEUTRAL,
    SOIL_REACTION_CALCAREOUS,
    SOIL_REACTION_SALINE_ALKALINE
} SdkSoilReactionClass;

typedef enum {
    SOIL_FERTILITY_VERY_LOW = 0,
    SOIL_FERTILITY_LOW,
    SOIL_FERTILITY_MODERATE,
    SOIL_FERTILITY_HIGH,
    SOIL_FERTILITY_VERY_HIGH
} SdkSoilFertilityClass;

typedef enum {
    SOIL_SALINITY_NONE = 0,
    SOIL_SALINITY_SLIGHT,
    SOIL_SALINITY_MODERATE,
    SOIL_SALINITY_HIGH
} SdkSoilSalinityClass;

typedef enum {
    ECOLOGY_BARREN = 0,
    ECOLOGY_DUNE_COAST,
    ECOLOGY_ESTUARY_WETLAND,
    ECOLOGY_RIPARIAN_FOREST,
    ECOLOGY_FLOODPLAIN_MEADOW,
    ECOLOGY_FEN,
    ECOLOGY_BOG,
    ECOLOGY_PRAIRIE,
    ECOLOGY_STEPPE,
    ECOLOGY_MEDITERRANEAN_SCRUB,
    ECOLOGY_TEMPERATE_DECIDUOUS_FOREST,
    ECOLOGY_TEMPERATE_CONIFER_FOREST,
    ECOLOGY_BOREAL_TAIGA,
    ECOLOGY_TROPICAL_SEASONAL_FOREST,
    ECOLOGY_TROPICAL_RAINFOREST,
    ECOLOGY_HOT_DESERT,
    ECOLOGY_TUNDRA,
    ECOLOGY_ALPINE_MEADOW,
    ECOLOGY_VOLCANIC_BARRENS,
    ECOLOGY_NIVAL_ICE,
    ECOLOGY_SALT_DESERT,
    ECOLOGY_SCRUB_BADLANDS,
    ECOLOGY_SAVANNA_GRASSLAND,
    ECOLOGY_MANGROVE_SWAMP
} SdkBiomeEcology;

/* Legacy aliases retained to ease migration to the expanded ecology set. */
#define ECOLOGY_GRASSLAND ECOLOGY_PRAIRIE
#define ECOLOGY_SHRUB_STEPPE ECOLOGY_STEPPE
#define ECOLOGY_TEMPERATE_FOREST ECOLOGY_TEMPERATE_DECIDUOUS_FOREST
#define ECOLOGY_BOREAL_FOREST ECOLOGY_BOREAL_TAIGA
#define ECOLOGY_RIPARIAN_WOODLAND ECOLOGY_RIPARIAN_FOREST
#define ECOLOGY_WETLAND_FEN ECOLOGY_FEN
#define ECOLOGY_PEAT_BOG ECOLOGY_BOG

typedef enum {
    RESOURCE_PROVINCE_NONE = 0,
    RESOURCE_PROVINCE_AGGREGATE_DISTRICT,
    RESOURCE_PROVINCE_CLAY_DISTRICT,
    RESOURCE_PROVINCE_CARBONATE_CEMENT_DISTRICT,
    RESOURCE_PROVINCE_COALFIELD,
    RESOURCE_PROVINCE_IRON_BELT,
    RESOURCE_PROVINCE_VOLCANIC_METALS,
    RESOURCE_PROVINCE_OIL_FIELD,
    RESOURCE_PROVINCE_COPPER_PORPHYRY_BELT,
    RESOURCE_PROVINCE_BAUXITE_DEPOSIT,
    RESOURCE_PROVINCE_RARE_EARTH_DISTRICT,
    RESOURCE_PROVINCE_URANIUM_GRANITE_BELT,
    RESOURCE_PROVINCE_SULFUR_VOLCANIC_DISTRICT,
    RESOURCE_PROVINCE_SALTPETER_NITRATE_FIELD,
    RESOURCE_PROVINCE_PHOSPHATE_DEPOSIT,
    RESOURCE_PROVINCE_STRATEGIC_ALLOY_BELT,
    RESOURCE_PROVINCE_LEAD_ZINC_DISTRICT
} SdkResourceProvince;

typedef enum {
    SDK_HYDROCARBON_NONE = 0,
    SDK_HYDROCARBON_OIL_SHALE,
    SDK_HYDROCARBON_OIL_SAND,
    SDK_HYDROCARBON_CRUDE_OIL,
    SDK_HYDROCARBON_NATURAL_GAS
} SdkHydrocarbonClass;

typedef enum {
    SURFACE_WATER_NONE = 0,
    SURFACE_WATER_OPEN,
    SURFACE_WATER_SEASONAL_ICE,
    SURFACE_WATER_PERENNIAL_ICE
} SdkSurfaceWaterClass;

typedef enum {
    SDK_LANDFORM_NONE          = 0u,
    SDK_LANDFORM_RIVER_CHANNEL = 1u << 0,
    SDK_LANDFORM_FLOODPLAIN    = 1u << 1,
    SDK_LANDFORM_RAVINE        = 1u << 2,
    SDK_LANDFORM_LAKE_BASIN    = 1u << 3,
    SDK_LANDFORM_CAVE_ENTRANCE = 1u << 4,
    SDK_LANDFORM_VOLCANIC_VENT = 1u << 5,
    SDK_LANDFORM_CALDERA       = 1u << 6,
    SDK_LANDFORM_LAVA_FIELD    = 1u << 7
} SdkLandformFlags;

typedef struct {
    int16_t base_height;
    int16_t surface_height;
    int16_t water_height;
    int16_t river_bed_height;
    uint8_t soil_depth;
    uint8_t sediment_depth;
    uint8_t sediment_thickness;
    uint8_t regolith_thickness;
    uint8_t river_order;
    uint8_t floodplain_width;
    SdkTerrainProvince terrain_province;
    SdkBedrockProvince bedrock_province;
    SdkTemperatureBand temperature_band;
    SdkMoistureBand moisture_band;
    SdkSurfaceSediment surface_sediment;
    SdkParentMaterialClass parent_material;
    SdkDrainageClass drainage_class;
    SdkSoilReactionClass soil_reaction;
    SdkSoilFertilityClass soil_fertility;
    SdkSoilSalinityClass soil_salinity;
    uint8_t water_table_depth;
    SdkSurfaceWaterClass water_surface_class;
    uint32_t landform_flags;
    SdkBiomeEcology ecology;
    SdkResourceProvince resource_province;
    SdkHydrocarbonClass hydrocarbon_class;
    uint8_t resource_grade;
} SdkTerrainColumnProfile;

typedef struct {
    float hydrocarbon_score;
    float coal_score;
    float iron_score;
    float carbonate_score;
    float clay_score;
    float sand_score;
    float timber_score;
    float sulfur_score;
} SdkResourceSignature;

#ifdef __cplusplus
}
#endif

#endif /* NQLSDK_WORLDGEN_TYPES_H */
